application: prueba
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: guestbook.application
  
libraries:							# Indicamos que estamos utilizando la librería
- name: webapp2						#   'webapp2' 
  version: latest