application: prueba
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: dibujarTabla.application
  
libraries:
- name: webapp2                     # Indicamos que estamos utilizando la librería 'webapp2'.
  version: latest